import { Language, TranslationKey, FAQItem, ManualStep } from './types';

// Emission Factors (Simplified for MVP, based on PL context where applicable)
export const EMISSION_FACTORS = {
  scope1: {
    naturalGas: 2.02, // kg CO2e per m3
    heatingOil: 3.19, // kg CO2e per liter
    coal: 2.42, // kg CO2e per kg
    diesel: 2.68, // kg CO2e per liter
    petrol: 2.31, // kg CO2e per liter
    refrigerants: 1810, // Average GWP
  },
  scope2: {
    electricity: 0.698, // kg CO2e per kWh
    districtHeating: 95.05, // kg CO2e per GJ
  },
  scope3: {
    water: 0.344, // kg CO2e per m3
    waste: 0.5, // kg CO2e per kg
    airTravelShort: 0.255, // kg CO2e per km
    airTravelLong: 0.150, // kg CO2e per km
    railTravel: 0.041, // kg CO2e per km
  },
};

export const FAQ_CONTENT: Record<Language, FAQItem[]> = {
  [Language.EN]: [
    { question: "What is Scope 1?", answer: "Direct emissions from owned or controlled sources (e.g., fuel combustion in company vehicles)." },
    { question: "What is Scope 2?", answer: "Indirect emissions from the generation of purchased energy (e.g., electricity, heating)." },
    { question: "How is the result calculated?", answer: "We use standard emission factors multiplied by your input consumption data." },
    { question: "Can I export the results?", answer: "Yes, use the Print / Save PDF button on the results screen to generate a signed report." },
  ],
  [Language.PL]: [
    { question: "Czym jest Zakres 1?", answer: "Bezpośrednie emisje z własnych lub kontrolowanych źródeł (np. spalanie paliw w pojazdach firmowych)." },
    { question: "Czym jest Zakres 2?", answer: "Pośrednie emisje z produkcji zakupionej energii (np. prąd, ciepło systemowe)." },
    { question: "Jak obliczany jest wynik?", answer: "Używamy standardowych wskaźników emisji pomnożonych przez podane dane o zużyciu." },
    { question: "Czy mogę pobrać raport?", answer: "Tak, użyj przycisku Drukuj / Zapisz PDF na ekranie wyników." },
  ],
  [Language.SK]: [
    { question: "Čo je Rozsah 1?", answer: "Priame emisie z vlastných zdrojov." },
    { question: "Čo je Rozsah 2?", answer: "Nepriame emisie z nakúpenej energie." },
    { question: "Ako sa počíta výsledok?", answer: "Používame emisné faktory vynásobené vašou spotrebou." },
    { question: "Môžem exportovať report?", answer: "Áno, na obrazovke výsledkov kliknite na tlačidlo Tlačiť / PDF." },
  ],
  [Language.DE]: [
    { question: "Was ist Scope 1?", answer: "Direkte Emissionen aus eigenen Quellen." },
    { question: "Was ist Scope 2?", answer: "Indirekte Emissionen aus eingekaufter Energie." },
    { question: "Wie wird das Ergebnis berechnet?", answer: "Wir verwenden Emissionsfaktoren multipliziert mit Ihrem Verbrauch." },
    { question: "Kann ich einen Bericht exportieren?", answer: "Ja, nutzen Sie den Button Drucken / PDF auf der Ergebnisseite." },
  ],
  [Language.IT]: [
    { question: "Cos'è Scope 1?", answer: "Emissioni dirette da fonti proprie." },
    { question: "Cos'è Scope 2?", answer: "Emissioni indirette da energia acquistata." },
    { question: "Come viene calcolato?", answer: "Usiamo fattori di emissione standard moltiplicati per il consumo." },
    { question: "Posso esportare i risultati?", answer: "Sì, premi il pulsante Stampa / PDF nella pagina risultati." },
  ],
  [Language.HR]: [
    { question: "Što je Opseg 1?", answer: "Izravne emisije iz vlastitih izvora." },
    { question: "Što je Opseg 2?", answer: "Neizravne emisije iz kupljene energije." },
    { question: "Kako se računa?", answer: "Koristimo faktore emisije pomnožene s potrošnjom." },
    { question: "Mogu li preuzeti izvješće?", answer: "Da, na stranici s rezultatima kliknite gumb Ispiši / PDF." },
  ],
};

export const USER_MANUAL_CONTENT: Record<Language, ManualStep[]> = {
  [Language.EN]: [
    { title: '1. Gather operational data', description: 'Open the spreadsheet provided by the ordering party and collect fuel, energy, travel, and waste data for the selected reporting year.' },
    { title: '2. Enter values per scope', description: 'Navigate through the Scope I, II, and III steps and enter the numeric values exactly as they appear in the spreadsheet.' },
    { title: '3. Validate calculations', description: 'Review the charts and breakdown table to confirm the totals align with your internal expectations.' },
    { title: '4. Generate the PDF report', description: 'Use the Print / Save PDF action, store the file in your document repository, and share it with stakeholders.' },
  ],
  [Language.PL]: [
    { title: '1. Przygotuj dane działalności', description: 'Otwórz przekazany arkusz i zbierz dane o paliwach, energii, podróżach i odpadach dla wybranego roku.' },
    { title: '2. Wprowadź wartości w zakresach', description: 'Przechodząc przez Zakres 1, 2 i 3 wpisuj liczby dokładnie tak, jak figurują w arkuszu.' },
    { title: '3. Zweryfikuj obliczenia', description: 'Sprawdź wykresy i tabelę udziałów, aby potwierdzić zgodność wyników z oczekiwaniami.' },
    { title: '4. Wygeneruj raport PDF', description: 'Użyj funkcji Drukuj / PDF, archiwizuj plik i przekaż go interesariuszom.' },
  ],
  [Language.SK]: [
    { title: '1. Pripravte údaje', description: 'Otvorte dodaný excel a zhromaždite údaje o palivách, energii, cestovaní a odpade.' },
    { title: '2. Zadajte hodnoty podľa rozsahov', description: 'V krokoch Rozsah 1-3 zapisujte hodnoty presne podľa zdrojového súboru.' },
    { title: '3. Skontrolujte výsledky', description: 'Porovnajte grafy a tabuľku s očakávaniami interného tímu.' },
    { title: '4. Vytvorte PDF report', description: 'Kliknite na Tlačiť / PDF, uložte súbor a distribuujte ho zainteresovaným stranám.' },
  ],
  [Language.DE]: [
    { title: '1. Betriebsdaten sammeln', description: 'Öffnen Sie die bereitgestellte Tabelle und sammeln Sie Energie-, Reise- und Abfalldaten des Berichtsjahres.' },
    { title: '2. Werte je Scope eingeben', description: 'Geben Sie die Zahlen in den Schritten Scope 1 bis 3 exakt wie in der Tabelle an.' },
    { title: '3. Ergebnisse prüfen', description: 'Vergleichen Sie Diagramme und Aufstellung mit den erwarteten Werten Ihres Teams.' },
    { title: '4. PDF-Bericht erzeugen', description: 'Nutzen Sie Drucken / PDF, archivieren Sie die Datei und teilen Sie sie mit Stakeholdern.' },
  ],
  [Language.IT]: [
    { title: '1. Raccogli i dati operativi', description: 'Apri il foglio fornito e reperisci dati su combustibili, energia, viaggi e rifiuti.' },
    { title: '2. Inserisci i valori per gli scope', description: 'Compila gli step Scope 1-3 riportando fedelmente i numeri del foglio.' },
    { title: '3. Verifica i risultati', description: 'Controlla grafici e tabella per confermare la correttezza dei totali.' },
    { title: '4. Genera il rapporto PDF', description: 'Usa Stampa / PDF, archivia il file e condividilo con gli stakeholder.' },
  ],
  [Language.HR]: [
    { title: '1. Prikupite operativne podatke', description: 'Otvorite dostavljenu tablicu i prikupite podatke o gorivu, energiji, putovanjima i otpadu.' },
    { title: '2. Unesite vrijednosti po opsegu', description: 'U koracima Opseg 1-3 unesite brojčane vrijednosti točno kao u tablici.' },
    { title: '3. Provjerite rezultate', description: 'Usporedite grafikone i tablicu s internim očekivanjima.' },
    { title: '4. Generirajte PDF izvješće', description: 'Kliknite Ispiši / PDF, spremite datoteku i podijelite je s dionicima.' },
  ],
};

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.EN]: {
    title: 'Carbon Footprint Calculator',
    subtitle: 'Calculate and visualize your environmental impact.',
    startCalc: 'Start Calculation',
    scope1: 'Scope 1: Direct',
    scope2: 'Scope 2: Energy',
    scope3: 'Scope 3: Indirect',
    results: 'Your Report',
    calculate: 'Calculate Results',
    next: 'Next Step',
    back: 'Back',
    naturalGas: 'Natural Gas',
    heatingOil: 'Heating Oil',
    coal: 'Coal',
    diesel: 'Fleet Diesel',
    petrol: 'Fleet Petrol',
    refrigerants: 'Refrigerants Refilled',
    electricity: 'Electricity Consumption',
    districtHeating: 'District Heating',
    water: 'Water Consumption',
    waste: 'Waste Generated',
    airTravelShort: 'Air Travel (< 500km)',
    airTravelLong: 'Air Travel (> 500km)',
    railTravel: 'Rail Travel',
    scope1Desc: 'Direct emissions from owned or controlled sources.',
    scope2Desc: 'Indirect emissions from the generation of purchased energy.',
    scope3Desc: 'All other indirect emissions in your value chain.',
    totalEmissions: 'Total Annual Emissions',
    downloadReport: 'Print / Save PDF',
    unit_m3: 'm³',
    unit_l: 'liters',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Home',
    menu_calc: 'Calculator',
    menu_history: 'History',
    menu_faq: 'FAQ',
    history_title: 'Calculation History',
    history_empty: 'No calculations yet. Start one now!',
    faq_title: 'User Manual & FAQ',
    a11y_contrast: 'High Contrast',
    a11y_font: 'Font Size',
    project_info_title: 'Project & Calculator Overview',
    project_info_body: 'Dedicated website explaining the calculator scope, data sources, and safeguards for carbon reporting.',
    hosting_title: 'Dedicated Hosting',
    hosting_body: 'Isolated infrastructure with SSL, monitoring, and nightly backups to satisfy the hosting requirement.',
    support_title: '5-Year Support & SLA',
    support_body: 'Includes technical maintenance, uptime monitoring, and assistance for at least five years.',
    design_title: 'Functional Graphic Design',
    design_body: 'Responsive layout with multilingual typography, WCAG-friendly contrast, and iconography for each scope.',
    stats_heading: 'Usage & Impact Statistics',
    stats_total_calcs: 'Total Calculations',
    stats_total_emissions: 'Total Emissions (kg CO₂e)',
    stats_avg_emission: 'Average per Calculation',
    stats_last_calc: 'Last Calculation',
    manual_heading: 'User Manual',
    manual_intro: 'Follow the guided steps below before consulting the FAQ.',
  },
  [Language.PL]: {
    title: 'Kalkulator Śladu Węglowego',
    subtitle: 'Oblicz i zwizualizuj swój wpływ na środowisko.',
    startCalc: 'Rozpocznij',
    scope1: 'Zakres 1: Bezpośrednie',
    scope2: 'Zakres 2: Energia',
    scope3: 'Zakres 3: Pośrednie',
    results: 'Twój Raport',
    calculate: 'Oblicz Wyniki',
    next: 'Dalej',
    back: 'Wstecz',
    naturalGas: 'Gaz Ziemny',
    heatingOil: 'Olej Opałowy',
    coal: 'Węgiel',
    diesel: 'Olej Napędowy (Flota)',
    petrol: 'Benzyna (Flota)',
    refrigerants: 'Czynniki Chłodnicze',
    electricity: 'Zużycie Energii Elektr.',
    districtHeating: 'Ciepło Systemowe',
    water: 'Zużycie Wody',
    waste: 'Wytworzone Odpady',
    airTravelShort: 'Loty (< 500km)',
    airTravelLong: 'Loty (> 500km)',
    railTravel: 'Podróże Kolejowe',
    scope1Desc: 'Bezpośrednie emisje z posiadanych lub kontrolowanych źródeł.',
    scope2Desc: 'Pośrednie emisje z produkcji zakupionej energii.',
    scope3Desc: 'Wszystkie inne pośrednie emisje w łańcuchu wartości.',
    totalEmissions: 'Całkowita Emisja Roczna',
    downloadReport: 'Drukuj / Zapisz PDF',
    unit_m3: 'm³',
    unit_l: 'litry',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Start',
    menu_calc: 'Kalkulator',
    menu_history: 'Historia',
    menu_faq: 'FAQ',
    history_title: 'Historia Obliczeń',
    history_empty: 'Brak obliczeń. Rozpocznij nowe!',
    faq_title: 'Instrukcja i FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Czcionka',
    project_info_title: 'Informacje o Projekcie i Kalkulatorze',
    project_info_body: 'Dedykowana witryna opisuje zakres kalkulatora, źródła danych oraz zabezpieczenia raportowe.',
    hosting_title: 'Dedykowany Hosting',
    hosting_body: 'Odizolowana infrastruktura z certyfikatem SSL, monitoringiem i kopiami zapasowymi.',
    support_title: '5‑letnie wsparcie techniczne',
    support_body: 'Zapewniamy utrzymanie, reagowanie na incydenty i pomoc użytkownikom przez minimum pięć lat.',
    design_title: 'Funkcjonalny projekt graficzny',
    design_body: 'Responsywny interfejs z przyjazną typografią, ikonami zakresów i wysokim kontrastem.',
    stats_heading: 'Statystyki Użytkowania',
    stats_total_calcs: 'Liczba obliczeń',
    stats_total_emissions: 'Skumulowane emisje (kg CO₂e)',
    stats_avg_emission: 'Średnia na obliczenie',
    stats_last_calc: 'Ostatnie obliczenie',
    manual_heading: 'Instrukcja użytkownika',
    manual_intro: 'Przed przejściem do FAQ wykonaj poniższe kroki.',
  },
  [Language.SK]: {
    title: 'Uhlíková Stopa Kalkulačka',
    subtitle: 'Vypočítajte a vizualizujte svoj dopad na životné prostredie.',
    startCalc: 'Začať',
    scope1: 'Rozsah 1: Priame',
    scope2: 'Rozsah 2: Energia',
    scope3: 'Rozsah 3: Nepriame',
    results: 'Vaša Správa',
    calculate: 'Vypočítať',
    next: 'Ďalej',
    back: 'Späť',
    naturalGas: 'Zemný Plyn',
    heatingOil: 'Vykurovací Olej',
    coal: 'Uhlie',
    diesel: 'Nafta',
    petrol: 'Benzín',
    refrigerants: 'Chladivá',
    electricity: 'Elektrická Energia',
    districtHeating: 'Diaľkové Vykurovanie',
    water: 'Spotreba Vody',
    waste: 'Odpad',
    airTravelShort: 'Let (< 500km)',
    airTravelLong: 'Let (> 500km)',
    railTravel: 'Vlak',
    scope1Desc: 'Priame emisie z vlastných zdrojov.',
    scope2Desc: 'Nepriame emisie z nakúpenej energie.',
    scope3Desc: 'Ostatné nepriame emisie.',
    totalEmissions: 'Celkové Emisie',
    downloadReport: 'Tlačiť / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Domov',
    menu_calc: 'Kalkulačka',
    menu_history: 'História',
    menu_faq: 'FAQ',
    history_title: 'História Výpočtov',
    history_empty: 'Žiadne údaje.',
    faq_title: 'Návod a FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Písmo',
    project_info_title: 'Informácie o projekte a kalkulačke',
    project_info_body: 'Dedikovaná stránka opisuje rozsah kalkulačky, zdroje dát a bezpečnostné zásady.',
    hosting_title: 'Dedikovaný hosting',
    hosting_body: 'Oddelená infraštruktúra so SSL, monitoringom a zálohami.',
    support_title: '5-ročná podpora',
    support_body: 'Technická údržba a pomoc používateľom je garantovaná minimálne päť rokov.',
    design_title: 'Funkčný grafický dizajn',
    design_body: 'Responzívne rozhranie s ikonami pre rozsahy a kontrastom podľa WCAG.',
    stats_heading: 'Štatistiky používania',
    stats_total_calcs: 'Počet výpočtov',
    stats_total_emissions: 'Súčet emisií (kg CO₂e)',
    stats_avg_emission: 'Priemer na výpočet',
    stats_last_calc: 'Posledný výpočet',
    manual_heading: 'Používateľský manuál',
    manual_intro: 'Pred čítaním FAQ postupujte podľa nasledujúcich krokov.',
  },
  [Language.DE]: {
    title: 'CO2-Fußabdruck Rechner',
    subtitle: 'Berechnen Sie Ihre Umweltauswirkungen.',
    startCalc: 'Starten',
    scope1: 'Scope 1: Direkt',
    scope2: 'Scope 2: Energie',
    scope3: 'Scope 3: Indirekt',
    results: 'Bericht',
    calculate: 'Berechnen',
    next: 'Weiter',
    back: 'Zurück',
    naturalGas: 'Erdgas',
    heatingOil: 'Heizöl',
    coal: 'Kohle',
    diesel: 'Diesel',
    petrol: 'Benzin',
    refrigerants: 'Kältemittel',
    electricity: 'Stromverbrauch',
    districtHeating: 'Fernwärme',
    water: 'Wasserverbrauch',
    waste: 'Abfall',
    airTravelShort: 'Flug (< 500km)',
    airTravelLong: 'Flug (> 500km)',
    railTravel: 'Bahnreisen',
    scope1Desc: 'Direkte Emissionen aus eigenen Quellen.',
    scope2Desc: 'Indirekte Emissionen aus eingekaufter Energie.',
    scope3Desc: 'Alle anderen indirekten Emissionen.',
    totalEmissions: 'Gesamtemissionen',
    downloadReport: 'Drucken / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Start',
    menu_calc: 'Rechner',
    menu_history: 'Verlauf',
    menu_faq: 'FAQ',
    history_title: 'Berechnungsverlauf',
    history_empty: 'Keine Berechnungen.',
    faq_title: 'Handbuch & FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Schrift',
    project_info_title: 'Projekt- und Rechnerinformationen',
    project_info_body: 'Die dedizierte Website beschreibt Umfang, Datengrundlagen und Sicherheitsmaßnahmen des Rechners.',
    hosting_title: 'Dediziertes Hosting',
    hosting_body: 'Getrennte Infrastruktur mit SSL, Monitoring und täglichen Backups.',
    support_title: '5 Jahre Support',
    support_body: 'Technischer Support, Wartung und Nutzerhilfe sind für mindestens fünf Jahre zugesichert.',
    design_title: 'Funktionales Grafikdesign',
    design_body: 'Responsives UI mit klarer Typografie, Piktogrammen und barrierefreien Farben.',
    stats_heading: 'Nutzungs- & Impact-Statistiken',
    stats_total_calcs: 'Anzahl Berechnungen',
    stats_total_emissions: 'Gesamtemissionen (kg CO₂e)',
    stats_avg_emission: 'Durchschnitt pro Berechnung',
    stats_last_calc: 'Letzte Berechnung',
    manual_heading: 'Benutzerhandbuch',
    manual_intro: 'Folgen Sie den untenstehenden Schritten, bevor Sie das FAQ lesen.',
  },
  [Language.IT]: {
    title: 'Calcolatore Impronta di Carbonio',
    subtitle: 'Calcola il tuo impatto ambientale.',
    startCalc: 'Inizia',
    scope1: 'Scope 1: Diretto',
    scope2: 'Scope 2: Energia',
    scope3: 'Scope 3: Indiretto',
    results: 'Risultato',
    calculate: 'Calcolare',
    next: 'Avanti',
    back: 'Indietro',
    naturalGas: 'Gas Naturale',
    heatingOil: 'Gasolio Riscaldamento',
    coal: 'Carbone',
    diesel: 'Diesel',
    petrol: 'Benzina',
    refrigerants: 'Refrigeranti',
    electricity: 'Elettricità',
    districtHeating: 'Teleriscaldamento',
    water: 'Acqua',
    waste: 'Rifiuti',
    airTravelShort: 'Volo (< 500km)',
    airTravelLong: 'Volo (> 500km)',
    railTravel: 'Treno',
    scope1Desc: 'Emissioni dirette da fonti di proprietà.',
    scope2Desc: 'Emissioni indirette da energia acquistata.',
    scope3Desc: 'Altre emissioni indirette.',
    totalEmissions: 'Emissioni Totali',
    downloadReport: 'Stampa / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Home',
    menu_calc: 'Calcolatrice',
    menu_history: 'Cronologia',
    menu_faq: 'FAQ',
    history_title: 'Cronologia Calcoli',
    history_empty: 'Nessun dato.',
    faq_title: 'Manuale e FAQ',
    a11y_contrast: 'Contrasto',
    a11y_font: 'Font',
    project_info_title: 'Informazioni su progetto e calcolatore',
    project_info_body: 'Il sito dedicato descrive l’ambito del calcolatore, le fonti dei dati e le misure di sicurezza.',
    hosting_title: 'Hosting dedicato',
    hosting_body: 'Infrastruttura isolata con SSL, monitoraggio e backup giornalieri.',
    support_title: 'Supporto tecnico di 5 anni',
    support_body: 'Manutenzione correttiva ed help desk garantiti per almeno cinque anni.',
    design_title: 'Design grafico funzionale',
    design_body: 'Interfaccia responsive con icone per gli ambiti e palette accessibile.',
    stats_heading: 'Statistiche di utilizzo',
    stats_total_calcs: 'Totale calcoli',
    stats_total_emissions: 'Emissioni complessive (kg CO₂e)',
    stats_avg_emission: 'Media per calcolo',
    stats_last_calc: 'Ultimo calcolo',
    manual_heading: 'Manuale utente',
    manual_intro: 'Segui i passaggi indicati prima di consultare le FAQ.',
  },
  [Language.HR]: {
    title: 'Kalkulator Ugljičnog Otiska',
    subtitle: 'Izračunajte svoj utjecaj na okoliš.',
    startCalc: 'Počni',
    scope1: 'Opseg 1: Izravno',
    scope2: 'Opseg 2: Energija',
    scope3: 'Opseg 3: Neizravno',
    results: 'Izvješće',
    calculate: 'Izračunaj',
    next: 'Dalje',
    back: 'Natrag',
    naturalGas: 'Prirodni Plin',
    heatingOil: 'Lož Ulje',
    coal: 'Ugljen',
    diesel: 'Dizel',
    petrol: 'Benzin',
    refrigerants: 'Rashladna Sredstva',
    electricity: 'Električna Energija',
    districtHeating: 'Grijanje',
    water: 'Voda',
    waste: 'Otpad',
    airTravelShort: 'Let (< 500km)',
    airTravelLong: 'Let (> 500km)',
    railTravel: 'Vlak',
    scope1Desc: 'Izravne emisije iz vlastitih izvora.',
    scope2Desc: 'Neizravne emisije iz kupljene energije.',
    scope3Desc: 'Ostale neizravne emisije.',
    totalEmissions: 'Ukupne Emisije',
    downloadReport: 'Ispiši / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Početna',
    menu_calc: 'Kalkulator',
    menu_history: 'Povijest',
    menu_faq: 'FAQ',
    history_title: 'Povijest Izračuna',
    history_empty: 'Nema podataka.',
    faq_title: 'Priručnik i FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Font',
    project_info_title: 'Informacije o projektu i kalkulatoru',
    project_info_body: 'Namjenska stranica opisuje opseg kalkulatora, izvore podataka i sigurnosne mjere.',
    hosting_title: 'Namjenski hosting',
    hosting_body: 'Odvojena infrastruktura sa SSL certifikatom, nadzorom i sigurnosnim kopijama.',
    support_title: '5 godina podrške',
    support_body: 'Tehnička podrška, održavanje i pomoć korisnicima dostupni su najmanje pet godina.',
    design_title: 'Funkcionalni grafički dizajn',
    design_body: 'Responzivno sučelje s ikonama opsega i paletom prilagođenom pristupačnosti.',
    stats_heading: 'Statistika korištenja',
    stats_total_calcs: 'Ukupno izračuna',
    stats_total_emissions: 'Ukupne emisije (kg CO₂e)',
    stats_avg_emission: 'Prosjek po izračunu',
    stats_last_calc: 'Zadnji izračun',
    manual_heading: 'Korisnički priručnik',
    manual_intro: 'Prije FAQ-a slijedite korake u nastavku.',
  },
};
