import { Language, TranslationKey, FAQItem } from './types';

// Emission Factors (Simplified for MVP, based on PL context where applicable)
export const EMISSION_FACTORS = {
  scope1: {
    naturalGas: 2.02, // kg CO2e per m3
    heatingOil: 3.19, // kg CO2e per liter
    coal: 2.42, // kg CO2e per kg
    diesel: 2.68, // kg CO2e per liter
    petrol: 2.31, // kg CO2e per liter
    refrigerants: 1810, // Average GWP
  },
  scope2: {
    electricity: 0.698, // kg CO2e per kWh
    districtHeating: 95.05, // kg CO2e per GJ
  },
  scope3: {
    water: 0.344, // kg CO2e per m3
    waste: 0.5, // kg CO2e per kg
    airTravelShort: 0.255, // kg CO2e per km
    airTravelLong: 0.150, // kg CO2e per km
    railTravel: 0.041, // kg CO2e per km
  },
};

export const FAQ_CONTENT: Record<Language, FAQItem[]> = {
  [Language.EN]: [
    { question: "What is Scope 1?", answer: "Direct emissions from owned or controlled sources (e.g., fuel combustion in company vehicles)." },
    { question: "What is Scope 2?", answer: "Indirect emissions from the generation of purchased energy (e.g., electricity, heating)." },
    { question: "How is the result calculated?", answer: "We use standard emission factors multiplied by your input consumption data." },
  ],
  [Language.PL]: [
    { question: "Czym jest Zakres 1?", answer: "Bezpośrednie emisje z własnych lub kontrolowanych źródeł (np. spalanie paliw w pojazdach firmowych)." },
    { question: "Czym jest Zakres 2?", answer: "Pośrednie emisje z produkcji zakupionej energii (np. prąd, ciepło systemowe)." },
    { question: "Jak obliczany jest wynik?", answer: "Używamy standardowych wskaźników emisji pomnożonych przez podane dane o zużyciu." },
  ],
  [Language.SK]: [
    { question: "Čo je Rozsah 1?", answer: "Priame emisie z vlastných zdrojov." },
    { question: "Čo je Rozsah 2?", answer: "Nepriame emisie z nakúpenej energie." },
    { question: "Ako sa počíta výsledok?", answer: "Používame emisné faktory vynásobené vašou spotrebou." },
  ],
  [Language.DE]: [
    { question: "Was ist Scope 1?", answer: "Direkte Emissionen aus eigenen Quellen." },
    { question: "Was ist Scope 2?", answer: "Indirekte Emissionen aus eingekaufter Energie." },
    { question: "Wie wird das Ergebnis berechnet?", answer: "Wir verwenden Emissionsfaktoren multipliziert mit Ihrem Verbrauch." },
  ],
  [Language.IT]: [
    { question: "Cos'è Scope 1?", answer: "Emissioni dirette da fonti proprie." },
    { question: "Cos'è Scope 2?", answer: "Emissioni indirette da energia acquistata." },
    { question: "Come viene calcolato?", answer: "Usiamo fattori di emissione standard moltiplicati per il consumo." },
  ],
  [Language.HR]: [
    { question: "Što je Opseg 1?", answer: "Izravne emisije iz vlastitih izvora." },
    { question: "Što je Opseg 2?", answer: "Neizravne emisije iz kupljene energije." },
    { question: "Kako se računa?", answer: "Koristimo faktore emisije pomnožene s potrošnjom." },
  ],
};

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.EN]: {
    title: 'Carbon Footprint Calculator',
    subtitle: 'Calculate and visualize your environmental impact.',
    startCalc: 'Start Calculation',
    scope1: 'Scope 1: Direct',
    scope2: 'Scope 2: Energy',
    scope3: 'Scope 3: Indirect',
    results: 'Your Report',
    calculate: 'Calculate Results',
    next: 'Next Step',
    back: 'Back',
    naturalGas: 'Natural Gas',
    heatingOil: 'Heating Oil',
    coal: 'Coal',
    diesel: 'Fleet Diesel',
    petrol: 'Fleet Petrol',
    refrigerants: 'Refrigerants Refilled',
    electricity: 'Electricity Consumption',
    districtHeating: 'District Heating',
    water: 'Water Consumption',
    waste: 'Waste Generated',
    airTravelShort: 'Air Travel (< 500km)',
    airTravelLong: 'Air Travel (> 500km)',
    railTravel: 'Rail Travel',
    scope1Desc: 'Direct emissions from owned or controlled sources.',
    scope2Desc: 'Indirect emissions from the generation of purchased energy.',
    scope3Desc: 'All other indirect emissions in your value chain.',
    totalEmissions: 'Total Annual Emissions',
    downloadReport: 'Print / Save PDF',
    unit_m3: 'm³',
    unit_l: 'liters',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Home',
    menu_calc: 'Calculator',
    menu_history: 'History',
    menu_faq: 'FAQ',
    history_title: 'Calculation History',
    history_empty: 'No calculations yet. Start one now!',
    faq_title: 'User Manual & FAQ',
    a11y_contrast: 'High Contrast',
    a11y_font: 'Font Size',
  },
  [Language.PL]: {
    title: 'Kalkulator Śladu Węglowego',
    subtitle: 'Oblicz i zwizualizuj swój wpływ na środowisko.',
    startCalc: 'Rozpocznij',
    scope1: 'Zakres 1: Bezpośrednie',
    scope2: 'Zakres 2: Energia',
    scope3: 'Zakres 3: Pośrednie',
    results: 'Twój Raport',
    calculate: 'Oblicz Wyniki',
    next: 'Dalej',
    back: 'Wstecz',
    naturalGas: 'Gaz Ziemny',
    heatingOil: 'Olej Opałowy',
    coal: 'Węgiel',
    diesel: 'Olej Napędowy (Flota)',
    petrol: 'Benzyna (Flota)',
    refrigerants: 'Czynniki Chłodnicze',
    electricity: 'Zużycie Energii Elektr.',
    districtHeating: 'Ciepło Systemowe',
    water: 'Zużycie Wody',
    waste: 'Wytworzone Odpady',
    airTravelShort: 'Loty (< 500km)',
    airTravelLong: 'Loty (> 500km)',
    railTravel: 'Podróże Kolejowe',
    scope1Desc: 'Bezpośrednie emisje z posiadanych lub kontrolowanych źródeł.',
    scope2Desc: 'Pośrednie emisje z produkcji zakupionej energii.',
    scope3Desc: 'Wszystkie inne pośrednie emisje w łańcuchu wartości.',
    totalEmissions: 'Całkowita Emisja Roczna',
    downloadReport: 'Drukuj / Zapisz PDF',
    unit_m3: 'm³',
    unit_l: 'litry',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Start',
    menu_calc: 'Kalkulator',
    menu_history: 'Historia',
    menu_faq: 'FAQ',
    history_title: 'Historia Obliczeń',
    history_empty: 'Brak obliczeń. Rozpocznij nowe!',
    faq_title: 'Instrukcja i FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Czcionka',
  },
  [Language.SK]: {
    title: 'Uhlíková Stopa Kalkulačka',
    subtitle: 'Vypočítajte a vizualizujte svoj dopad na životné prostredie.',
    startCalc: 'Začať',
    scope1: 'Rozsah 1: Priame',
    scope2: 'Rozsah 2: Energia',
    scope3: 'Rozsah 3: Nepriame',
    results: 'Vaša Správa',
    calculate: 'Vypočítať',
    next: 'Ďalej',
    back: 'Späť',
    naturalGas: 'Zemný Plyn',
    heatingOil: 'Vykurovací Olej',
    coal: 'Uhlie',
    diesel: 'Nafta',
    petrol: 'Benzín',
    refrigerants: 'Chladivá',
    electricity: 'Elektrická Energia',
    districtHeating: 'Diaľkové Vykurovanie',
    water: 'Spotreba Vody',
    waste: 'Odpad',
    airTravelShort: 'Let (< 500km)',
    airTravelLong: 'Let (> 500km)',
    railTravel: 'Vlak',
    scope1Desc: 'Priame emisie z vlastných zdrojov.',
    scope2Desc: 'Nepriame emisie z nakúpenej energie.',
    scope3Desc: 'Ostatné nepriame emisie.',
    totalEmissions: 'Celkové Emisie',
    downloadReport: 'Tlačiť / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Domov',
    menu_calc: 'Kalkulačka',
    menu_history: 'História',
    menu_faq: 'FAQ',
    history_title: 'História Výpočtov',
    history_empty: 'Žiadne údaje.',
    faq_title: 'Návod a FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Písmo',
  },
  [Language.DE]: {
    title: 'CO2-Fußabdruck Rechner',
    subtitle: 'Berechnen Sie Ihre Umweltauswirkungen.',
    startCalc: 'Starten',
    scope1: 'Scope 1: Direkt',
    scope2: 'Scope 2: Energie',
    scope3: 'Scope 3: Indirekt',
    results: 'Bericht',
    calculate: 'Berechnen',
    next: 'Weiter',
    back: 'Zurück',
    naturalGas: 'Erdgas',
    heatingOil: 'Heizöl',
    coal: 'Kohle',
    diesel: 'Diesel',
    petrol: 'Benzin',
    refrigerants: 'Kältemittel',
    electricity: 'Stromverbrauch',
    districtHeating: 'Fernwärme',
    water: 'Wasserverbrauch',
    waste: 'Abfall',
    airTravelShort: 'Flug (< 500km)',
    airTravelLong: 'Flug (> 500km)',
    railTravel: 'Bahnreisen',
    scope1Desc: 'Direkte Emissionen aus eigenen Quellen.',
    scope2Desc: 'Indirekte Emissionen aus eingekaufter Energie.',
    scope3Desc: 'Alle anderen indirekten Emissionen.',
    totalEmissions: 'Gesamtemissionen',
    downloadReport: 'Drucken / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Start',
    menu_calc: 'Rechner',
    menu_history: 'Verlauf',
    menu_faq: 'FAQ',
    history_title: 'Berechnungsverlauf',
    history_empty: 'Keine Berechnungen.',
    faq_title: 'Handbuch & FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Schrift',
  },
  [Language.IT]: {
    title: 'Calcolatore Impronta di Carbonio',
    subtitle: 'Calcola il tuo impatto ambientale.',
    startCalc: 'Inizia',
    scope1: 'Scope 1: Diretto',
    scope2: 'Scope 2: Energia',
    scope3: 'Scope 3: Indiretto',
    results: 'Risultato',
    calculate: 'Calcolare',
    next: 'Avanti',
    back: 'Indietro',
    naturalGas: 'Gas Naturale',
    heatingOil: 'Gasolio Riscaldamento',
    coal: 'Carbone',
    diesel: 'Diesel',
    petrol: 'Benzina',
    refrigerants: 'Refrigeranti',
    electricity: 'Elettricità',
    districtHeating: 'Teleriscaldamento',
    water: 'Acqua',
    waste: 'Rifiuti',
    airTravelShort: 'Volo (< 500km)',
    airTravelLong: 'Volo (> 500km)',
    railTravel: 'Treno',
    scope1Desc: 'Emissioni dirette da fonti di proprietà.',
    scope2Desc: 'Emissioni indirette da energia acquistata.',
    scope3Desc: 'Altre emissioni indirette.',
    totalEmissions: 'Emissioni Totali',
    downloadReport: 'Stampa / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Home',
    menu_calc: 'Calcolatrice',
    menu_history: 'Cronologia',
    menu_faq: 'FAQ',
    history_title: 'Cronologia Calcoli',
    history_empty: 'Nessun dato.',
    faq_title: 'Manuale e FAQ',
    a11y_contrast: 'Contrasto',
    a11y_font: 'Font',
  },
  [Language.HR]: {
    title: 'Kalkulator Ugljičnog Otiska',
    subtitle: 'Izračunajte svoj utjecaj na okoliš.',
    startCalc: 'Počni',
    scope1: 'Opseg 1: Izravno',
    scope2: 'Opseg 2: Energija',
    scope3: 'Opseg 3: Neizravno',
    results: 'Izvješće',
    calculate: 'Izračunaj',
    next: 'Dalje',
    back: 'Natrag',
    naturalGas: 'Prirodni Plin',
    heatingOil: 'Lož Ulje',
    coal: 'Ugljen',
    diesel: 'Dizel',
    petrol: 'Benzin',
    refrigerants: 'Rashladna Sredstva',
    electricity: 'Električna Energija',
    districtHeating: 'Grijanje',
    water: 'Voda',
    waste: 'Otpad',
    airTravelShort: 'Let (< 500km)',
    airTravelLong: 'Let (> 500km)',
    railTravel: 'Vlak',
    scope1Desc: 'Izravne emisije iz vlastitih izvora.',
    scope2Desc: 'Neizravne emisije iz kupljene energije.',
    scope3Desc: 'Ostale neizravne emisije.',
    totalEmissions: 'Ukupne Emisije',
    downloadReport: 'Ispiši / PDF',
    unit_m3: 'm³',
    unit_l: 'l',
    unit_kg: 'kg',
    unit_kwh: 'kWh',
    unit_gj: 'GJ',
    unit_km: 'km',
    menu_home: 'Početna',
    menu_calc: 'Kalkulator',
    menu_history: 'Povijest',
    menu_faq: 'FAQ',
    history_title: 'Povijest Izračuna',
    history_empty: 'Nema podataka.',
    faq_title: 'Priručnik i FAQ',
    a11y_contrast: 'Kontrast',
    a11y_font: 'Font',
  },
};
